#
# /etc/ddclient.conf
#

# Router
# use=web, web=ipify-ipv4
# use=web, web='https://cloudflare.com/cdn-cgi/trace', web-skip='ip='
use=web, web='https://1.1.1.1/cdn-cgi/trace', web-skip='ip='

# Cloudflare
protocol=cloudflare
password=
# ifconfig.me,ip.sb

# example.com
zone=example.com
*.example.com,d.example.com

# example2.vn
# zone=example2.vn
# *.example2.vn,d.example2.vn
