[env]

GOTOOLCHAIN = "local"

[tools]

usage = "latest"

# Common
jq = "latest"
yq = "latest"
just = "latest"
caddy = "latest"
buf = "latest"
mkcert = "latest"
github-cli = "latest"
terraform = "latest"
rust = "latest"
zig = "latest"

# AI
claude-code = "latest"
opencode = "latest"

# Node
bun = "latest"
node = "24"

neovim = "latest"
gdu = "latest"


# Golang
go = "latest"
watchexec = "latest"

# Flutter
flutter = "latest"
java = "21"
android-sdk = "latest"
cmake = "latest"
ninja = "latest"

# Game
godot = "latest"
