[env]
GOTOOLCHAIN = "local"

[tools]
flutter = "latest"
usage = "latest"
yq = "latest"
buf = "latest"
android-sdk = "latest"
cmake = "latest"
github-cli = "latest"
terraform = "latest"
bun = "latest"
mkcert = "latest"
jq = "latest"
rust = "latest"
java = "21"
zig = "latest"
ninja = "latest"
godot = "latest"
watchexec = "latest"
go = "latest"
node = "24"
just = "latest"
