[tools]
flutter = "latest"
usage = "latest"
java = "18"
yq = "latest"
buf = "latest"
android-sdk = "latest"
godot = "latest"
ninja = "latest"
cmake = "latest"
node = "22"
go = "latest"
github-cli = "latest"
terraform = "latest"
bun = "latest"
mkcert = "latest"
